[package]
name = "easy_storage"
version = "0.1.0"
edition = "2024"

# [features]
# json_parse = ["dep:serde_json"]
# toml_parse = ["dep:toml"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.9.5"}
serde_json = { version = "1.0.142"}

